<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.codesight</groupId>
        <artifactId>codesight_backend</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>relation</artifactId>
    <name>relation</name>
    <description>relation</description>

    <dependencies>
        <!-- Common -->
        <dependency>
            <groupId>com.codesight</groupId>
            <artifactId>common</artifactId>
        </dependency>

        <!-- Counter -->
        <dependency>
            <groupId>com.codesight</groupId>
            <artifactId>counter</artifactId>
        </dependency>

        <!-- MyBatis-Plus -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>

    </dependencies>

</project>
