spring:
  application:
    name: codesight_backend
  profiles:
    include: auth, storage
  datasource:
    url: jdbc:mysql://localhost:3306/codesight?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
        ack-mode: manual_immediate
  threads:
    virtual:
      enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

app:
  cache:
    caffeine:
      article-detail:
        initial-capacity: 100
        max-size: 10000
        ttl-seconds: 300
      author-card:
        initial-capacity: 100
        max-size: 5000
        ttl-seconds: 300
      category:
        initial-capacity: 10
        max-size: 500
        ttl-seconds: 600